import { FaFacebookF, FaInstagramSquare, FaList, FaPinterestP, FaLinkedinIn, FaClipboardList } from "react-icons/fa";
import {
  BsTwitter,
  BsPinterest,
  BsFillBagHeartFill,
  BsStarHalf,
  BsStarFill,
  BsFillTelephoneFill,
  BsDiscord,
  BsPencilSquare,
  BsClipboardHeart,
} from "react-icons/bs";
import {
  AiOutlineGoogle,
  AiFillPhone,
  AiOutlineHeart,
  AiOutlineMenu,
  AiOutlineEye,
  AiOutlineMenuUnfold,
  AiFillHeart,
  AiFillMail,
  AiFillInstagram,
  AiOutlineClose,
  AiFillCaretDown,
  AiOutlineLoading3Quarters,
  AiOutlineUser,
  AiOutlineArrowRight,
  AiOutlineOrderedList,
  AiOutlineLeft,
  AiOutlineRight,
  AiOutlineLogin,
  AiOutlineTwitter,
} from "react-icons/ai";
import { IoIosMail } from "react-icons/io";
import { HiMail, HiShoppingCart } from "react-icons/hi";
import { ImLocation2, ImGooglePlus, ImHome } from "react-icons/im";
import { GrUserAdmin } from "react-icons/gr";
import { RiAdminLine } from "react-icons/ri";
import { MdEmail } from "react-icons/md";
const icons = {
  AiOutlineMenuUnfold,
  AiOutlineEye,
  AiFillPhone,
  AiOutlineMenu,
  AiFillHeart,
  AiOutlineHeart,
  AiOutlineGoogle,
  FaFacebookF,
  FaInstagramSquare,
  BsTwitter,
  BsPinterest,
  BsFillBagHeartFill,
  BsStarFill,
  BsStarHalf,
  HiMail,
  HiShoppingCart,
  FaList,
  IoIosMail,
  ImLocation2,
  BsFillTelephoneFill,
  AiFillMail,
  BsDiscord,
  ImGooglePlus,
  FaPinterestP,
  FaLinkedinIn,
  AiFillInstagram,
  AiOutlineClose,
  AiFillCaretDown,
  AiOutlineLoading3Quarters,
  AiOutlineUser,
  BsPencilSquare,
  BsClipboardHeart,
  FaClipboardList,
  AiOutlineArrowRight,
  AiOutlineOrderedList,
  ImHome,
  AiOutlineLeft,
  AiOutlineRight,
  AiOutlineLogin,
  RiAdminLine,
  GrUserAdmin,
  AiOutlineTwitter,
  MdEmail,
};

export default icons;
